### ISSUE TITLE
FR & EN in the french article

### ISSUE THREAD

**Issue by jonathanChvn** [Allsimon/perf#1]
In https://github.com/Allsimon/perf/blob/master/doc/cpu/branch/branch-effect-fr.md

Scroll to "Exemple"

"L'astuce typique pour transformer du code avec branche en code "branchless" est d'utiliser un masque binaire pour ignorer certaines parties d'une équation.

The typical trick to transform branchy code to branchless code is to use binary mask to ignore parts of an equation."

You should remove the english text

**Comment by Allsimon** [comment]
Thanks a lot ! I fixed it in 7663d59
